architecture:
  operations: [none, skip, pool_avg_3, pool_max_3, conv_sep_3, conv_sep_5, conv_dil_2_3, conv_dil_2_5]
  mixed_type: mixed_gumbel
  shared_alphas: True
  depth: 8
  steps: 4
  initial_filters: 16

  hard:
    train:
      cell: False
      mixed: False
    valid:
      cell: False
      mixed: False
    test:
      cell: False
      mixed: True

  alphas:
    initial: 'random'

optimizers:
  theta:
    lr: 0.025
    momentum: 0.9
    weight_decay: 0.0003
    nesterov: False
  alpha:
    lr: 0.0003
    betas: [0.5, 0.999]
    weight_decay: 0.001
    amsgrad: False

annealing:
  tau_before: 'lambda e, last_epoch: max(0.01, 1 * math.exp(-0.03 * e))'
  tau: 'lambda e, last_epoch: 0.01 + (1.0 - 0.01) * (1 + math.cos(math.pi * e / last_epoch)) / 2'
  beta: 'lambda e, last_epoch: 0.25'
